baseURL = 'http://drepo.eth/'
languageCode = 'en-us'
title = 'dRepo.eth - decentralized Software Repository'

disableKinds = ['section', 'taxonomy', 'term', 'RSS']
uglyurls = false
relativeURLs = false
enableGitInfo = true

[menu]
[[menu.main]]
  identifier = 'intro'
  name = 'Introduction'
  weight = 100
[[menu.main]]
  identifier = 'repositories'
  name = 'Existing Repos'
  weight = 200
[[menu.main]]
  identifier = 'decentralization'
  name = 'Decentralization'
  weight = 300
[[menu.main]]
  identifier = 'drepo'
  name = 'Decentralized Repository'
  weight = 400
[[menu.main]]
  identifier = 'extension'
  name = 'Repository Extensions'
  weight = 500

[params]
  mainContent = 'drepo'

[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "node_modules/@fontsource/overpass-mono/files"
    target = "static/files"
  [[module.mounts]]
    source = "node_modules/@fontsource/ibm-plex-serif/files"
    target = "static/files"
  [[module.mounts]]
    source = "node_modules/bootstrap-icons/font/fonts"
    target = "static/files"

[markup]
  [markup.highlight]
    noclasses = false