baseURL = 'http://drepo.eth/'
languageCode = 'en-us'
title = 'dRepo.eth - Decentralized Software Repository'

disableKinds = ['section', 'taxonomy', 'term', 'RSS']
uglyurls = false
relativeURLs = false
enableGitInfo = true

[params]
  keywords = 'decentralized software repository, dRepo, software repository, repository, software, decentralized'
  homeSubtitle = 'The concept of a decentralized software repository guarantees the free distribution of open-source software and represents an essential building block for a censorship-resistant and user-owned internet'
  mainContent = 'drepo'

[menu]
[[menu.main]]
  identifier = 'intro'
  name = 'Introduction'
  weight = 100
[[menu.main]]
  identifier = 'decentralization'
  name = '(De-)centralization'
  weight = 200
[[menu.main]]
  identifier = 'repositories'
  name = 'Existing Repos'
  weight = 300
[[menu.main]]
  identifier = 'drepo'
  name = 'Decentralized Repository'
  weight = 400
[[menu.main]]
  identifier = 'expanded'
  name = 'Expanded Repository'
  weight = 500
[[menu.main]]
  identifier = 'web31'
  name = 'Next: Web 3.1'
  weight = 600

[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "node_modules/@fontsource/overpass-mono/files"
    target = "static/files"
  [[module.mounts]]
    source = "node_modules/@fontsource/ibm-plex-serif/files"
    target = "static/files"
  [[module.mounts]]
    source = "node_modules/bootstrap-icons/font/fonts"
    target = "static/files"

[markup]
  [markup.highlight]
    noclasses = false