baseURL = 'http://drepo.eth/'
languageCode = 'en-us'
title = 'dRepo - decentralized Software Repository'

disableKinds = ['section', 'taxonomy', 'term', 'RSS']
uglyurls = false

[menu]
[[menu.main]]
  identifier = 'intro'
  name = 'Introduction'
  weight = 100
[[menu.main]]
  identifier = 'repositories'
  name = 'Existing Repos'
  weight = 200
[[menu.main]]
  identifier = 'decentralization'
  name = 'Decentralization'
  weight = 300

[params]
  mainContent = 'drepo'

[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "node_modules/@fontsource/press-start-2p/files"
    target = "static/files"
  [[module.mounts]]
    source = "node_modules/@fontsource/fira-sans/files"
    target = "static/files"
  [[module.mounts]]
    source = "node_modules/@fontsource/overpass-mono/files"
    target = "static/files"
  [[module.mounts]]
    source = "node_modules/bootstrap-icons/font/fonts"
    target = "static/files"
