name: Node.js CI

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_REPO: ${{ github.repository }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - uses: actions/cache@v3
      with:
        path: |
          ~/.npm
          node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Package
      run: zip -r release-$(date +'%Y%m%d%H%M%S')-${{ github.sha }}.zip public
    - name: Publish as latest tag
      run: |
        gh release delete latest --yes || true
        git push origin :latest || true
        gh release create 'latest' -t 'latest' --prerelease release*
