name: Master Draft Deploy

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - uses: actions/cache@v3
      with:
        path: |
          ~/.npm
          node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build-draft
    - name: Package artifacts for deployment
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: |
          public

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v3
      with:
        ref: deployed
    - name: Unpack artifacts
      uses: actions/download-artifact@v4
      with:
        name: artifacts
        path: public
    - name: remove old deployment (keep CNAME file)
      run: |
        ls -l docs
        find docs/ ! -name 'CNAME' -type f -exec rm -rf {} +
        ls -l docs
    - name: copy new deployment
      run: |
        ls -l public
        cp -r public/* docs/
        ls -l docs
    - name: commit and push deployment
      run: |
        git config user.name drepo-github-actions
        git config user.email github-actions@drepo.eth
        git add docs
        git diff-index --quiet HEAD || git commit -m "Deploy build $GITHUB_SHA"
        git push